Repository neild3r/vscode-php-docblocker, pull requests merged in 2021-09, with the labels that each got.

#184 Trailing comma
  CHANGELOG.md
  src/block.ts
  src/block/function.ts
  test/fixtures/functions.php
  test/fixtures/functions.php.json
Labels: ready to merge, syntax

#187 v2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release candidate

#198 v2.5.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release candidate

#161 Feature | Implement settings for aligning params and return statements
  .vscode/launch.json
  CHANGELOG.md
  README.md
  package.json
  src/doc.ts
  test/completions.test.ts
  test/fixtures/doc.json
Labels: testing, feature, in progress

#205 v2.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release candidate
